<?php
section('Reader: GET /parishes');
reset_state();
make_parish('st-bede', 'approved', 'code', 'episcopal/western-oregon', "St. Bede's");
make_parish('grace', 'approved', 'public', 'episcopal/western-oregon', 'Grace Church');
make_parish('zion', 'approved', 'public', 'episcopal/olympia', 'Zion Church');
make_parish('waiting', 'pending', 'public', 'episcopal/western-oregon');
make_parish('banned', 'suspended', 'public', 'episcopal/western-oregon');
[$s, $b] = http('GET', '/api/v1/parishes');
$slugs = array_column(jbody($b)['parishes'] ?? [], 'slug');
t('lists approved parishes alphabetically by name', $s === 200 && $slugs === ['grace', 'st-bede', 'zion'], json_encode($slugs));
t('pending and suspended parishes never listed', !in_array('waiting', $slugs, true) && !in_array('banned', $slugs, true));
$first = jbody($b)['parishes'][1];
t('listing exposes only slug, name, diocese_key, corpus_parish_slug, visibility', array_keys($first) === ['slug', 'name', 'diocese_key', 'corpus_parish_slug', 'visibility'], json_encode(array_keys($first)));
[$s, $b] = http('GET', '/api/v1/parishes?diocese=episcopal/western-oregon');
t('diocese filter', array_column(jbody($b)['parishes'], 'slug') === ['grace', 'st-bede']);
[$s, $b] = http('GET', '/api/v1/parishes?diocese=' . rawurlencode("' OR 1=1 --"));
t('SQL-injection string in diocese -> 422, not executed', $s === 422 && (jbody($b)['error'] ?? '') === 'invalid_input', "$s $b");
[$s, $b] = http('GET', '/api/v1/parishes?diocese=episcopal/nowhere');
t('unknown diocese -> empty list', $s === 200 && jbody($b)['parishes'] === []);

section('Reader: GET /parishes/{slug}/intentions (public parish)');
reset_state();
[$gid] = make_parish('grace', 'approved', 'public', null, 'Grace Church');
[$zid] = make_parish('zion', 'approved', 'public', null, 'Zion Church');
$fam = make_intention($gid, 'family', 'The Smith family', 86400 * 5);
$ind2 = make_intention($gid, 'individual', 'Second person', 86400 * 5);
$ind1 = make_intention($gid, 'individual', 'First person', 86400 * 5);
$pdo->exec("UPDATE intentions SET created_at = created_at - INTERVAL 1 HOUR WHERE id = $ind1");
make_intention($gid, 'institution', 'A hospital', 86400 * 5);
make_intention($gid, 'situation', 'Peace in our city', 86400 * 5);
make_intention($gid, 'individual', 'EXPIRED yesterday', -86400);
make_intention($gid, 'individual', 'EXPIRED one second ago', -1);
make_intention($zid, 'individual', 'Only in Zion', 86400);
[$s, $b, $h] = http('GET', '/api/v1/parishes/grace/intentions');
$d = jbody($b);
$texts = array_column($d['intentions'] ?? [], 'text');
t('public parish serves without a pass', $s === 200, "$s");
t('ordered by category then created_at', $texts === ['First person', 'Second person', 'The Smith family', 'Peace in our city', 'A hospital'], json_encode($texts));
t('expired rows never returned, though they exist in the table',
    !in_array('EXPIRED yesterday', $texts, true) && !in_array('EXPIRED one second ago', $texts, true)
    && (int)$pdo->query("SELECT COUNT(*) FROM intentions WHERE body LIKE 'EXPIRED%'")->fetchColumn() === 2);
t('item shape is {id, category, text, expires_at}', array_keys($d['intentions'][0]) === ['id', 'category', 'text', 'expires_at']);
t('expires_at is ISO-8601 UTC with Z', preg_match('/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$/', $d['intentions'][0]['expires_at']) === 1);
t('response carries parish name and generated_at', ($d['parish'] ?? []) === ['slug' => 'grace', 'name' => 'Grace Church'] && isset($d['generated_at']));
t('intentions are cacheable privately for 60s', ($h['cache-control'] ?? '') === 'private, max-age=60', $h['cache-control'] ?? '');
t("another parish's items never appear", !in_array('Only in Zion', $texts, true));
[$s, $b] = http('GET', '/api/v1/parishes/zion/intentions');
t('and the other way round', array_column(jbody($b)['intentions'], 'text') === ['Only in Zion']);
[$s] = http('GET', '/api/v1/parishes/no-such-parish/intentions');
t('unknown parish -> 404', $s === 404);
[$s] = http('GET', '/api/v1/parishes/' . rawurlencode("x' OR '1'='1") . '/intentions');
t('injection-shaped slug -> 404', $s === 404);
[$s] = http('GET', '/api/v1/parishes/UPPERCASE/intentions');
t('non-canonical slug -> 404', $s === 404);

section('Reader: pending and suspended parishes serve nothing');
reset_state();
[$pid] = make_parish('waiting', 'pending', 'public');
[$xid] = make_parish('banned', 'suspended', 'public');
make_intention($pid, 'individual', 'hidden', 86400); make_intention($xid, 'individual', 'hidden', 86400);
[$s] = http('GET', '/api/v1/parishes/waiting/intentions');
t('pending parish -> 404', $s === 404);
[$s] = http('GET', '/api/v1/parishes/banned/intentions');
t('suspended parish -> 404', $s === 404);
[$s] = http('POST', '/api/v1/parishes/waiting/join', [], ['code' => 'ABCD-EFGH']);
t('cannot join a pending parish', $s === 404);
$pdo->exec("UPDATE parishes SET status='approved' WHERE slug='banned'");
[$s] = http('GET', '/api/v1/parishes/banned/intentions');
t('...and un-suspending restores service', $s === 200);
$pdo->exec("UPDATE parishes SET status='suspended' WHERE slug='banned'");

section('Reader: join codes and passes (code-required parish)');
reset_state();
[$aid, $aCode] = make_parish('alpha', 'approved', 'code', null, 'Alpha');
[$bid, $bCode] = make_parish('beta', 'approved', 'code', null, 'Beta');
make_intention($aid, 'individual', 'Alpha item', 86400);
make_intention($bid, 'individual', 'Beta item', 86400);
[$s, $b] = http('GET', '/api/v1/parishes/alpha/intentions');
t('no pass -> 401 code_required', $s === 401 && (jbody($b)['error'] ?? '') === 'code_required', "$s $b");
[$s, $b] = http('GET', '/api/v1/parishes/alpha/intentions', ['X-Parish-Pass: not-a-pass']);
t('garbage pass -> 401 code_required', $s === 401 && (jbody($b)['error'] ?? '') === 'code_required');
[$s, $b] = http('POST', '/api/v1/parishes/alpha/join', [], ['code' => 'ZZZZ-ZZZZ']);
t('wrong code -> 403 generic', $s === 403 && (jbody($b)['error'] ?? '') === 'forbidden' && strpos($b, 'ZZZZ') === false, "$s $b");
[$s2, $b2] = http('POST', '/api/v1/parishes/alpha/join', [], ['code' => 'not even a code']);
t('malformed code gives the identical response', $s2 === 403 && $b2 === $b);
[$s, $b] = http('POST', '/api/v1/parishes/alpha/join', [], ['nothing' => 1]);
t('missing code -> same 403', $s === 403);
[$s] = http('POST', '/api/v1/parishes/alpha/join', ['Content-Type: text/plain'], null);
t('no JSON body -> 400', $s === 400);
[$s, $b] = http('POST', '/api/v1/parishes/alpha/join', [], ['code' => strtolower(Crypto::formatJoinCode($aCode))]);
$join = jbody($b);
t('right code (lowercase, hyphenated) -> 200 with pass', $s === 200 && !empty($join['pass']) && ($join['parish']['slug'] ?? '') === 'alpha', "$s $b");
$passA = $join['pass'] ?? '';
[$s, $b] = http('GET', '/api/v1/parishes/alpha/intentions', ["X-Parish-Pass: $passA"]);
t('pass unlocks the parish', $s === 200 && array_column(jbody($b)['intentions'], 'text') === ['Alpha item']);
[$s, $b] = http('GET', '/api/v1/parishes/beta/intentions', ["X-Parish-Pass: $passA"]);
t("alpha's pass is rejected by beta", $s === 401);
$pdo->exec('UPDATE parishes SET join_code_version = join_code_version + 1 WHERE id = ' . $aid);
[$s] = http('GET', '/api/v1/parishes/alpha/intentions', ["X-Parish-Pass: $passA"]);
t('rotating the code invalidates every earlier pass', $s === 401);
$fresh = Crypto::makePass($aid, 2);
[$s] = http('GET', '/api/v1/parishes/alpha/intentions', ["X-Parish-Pass: $fresh"]);
t('a pass for the new version works', $s === 200);
$old = Crypto::makePass($aid, 2, time() - 366 * 86400);
[$s] = http('GET', '/api/v1/parishes/alpha/intentions', ["X-Parish-Pass: $old"]);
t('a pass older than 365 days is rejected', $s === 401);
$stored = $pdo->query("SELECT join_code_enc FROM parishes WHERE id = $aid")->fetchColumn();
t('join code is stored encrypted, never plaintext', strpos((string)$stored, $aCode) === false && strlen((string)$stored) > 24);
$public = make_parish('open', 'approved', 'public');
[$s] = http('POST', '/api/v1/parishes/open/join', [], ['code' => 'ABCD-EFGH']);
t('joining a public parish is refused politely (400)', $s === 400);

section('Reader: rate limits');
reset_state();
make_parish('limited', 'approved', 'code');
$codes = [];
for ($i = 1; $i <= 11; $i++) { [$codes[]] = http('POST', '/api/v1/parishes/limited/join', [], ['code' => 'ZZZZ-ZZZZ']); }
t('join: first 10 attempts answered normally (403)', count(array_filter(array_slice($codes, 0, 10), fn($c) => $c === 403)) === 10, json_encode($codes));
t('join: 11th attempt in the hour -> 429', $codes[10] === 429);
[$s, $b, $h] = http('POST', '/api/v1/parishes/limited/join', [], ['code' => 'ZZZZ-ZZZZ']);
t('429 carries Retry-After and a generic body', $s === 429 && (int)($h['retry-after'] ?? 0) > 0 && (jbody($b)['error'] ?? '') === 'rate_limited');
make_parish('other-parish', 'approved', 'code');
[$s] = http('POST', '/api/v1/parishes/other-parish/join', [], ['code' => 'ZZZZ-ZZZZ']);
t('the join limit is per IP+parish (another parish still answers)', $s === 403);
reset_state();
make_parish('busy', 'approved', 'public');
$pdo->exec("UPDATE rate_limits SET hits = 0");
$codes = [];
for ($i = 1; $i <= 3; $i++) { [$codes[]] = http('GET', '/api/v1/parishes/busy/intentions'); }
$pdo->exec("UPDATE rate_limits SET hits = 300, window_start = UTC_TIMESTAMP() WHERE bucket LIKE 'readip:%'");
[$s] = http('GET', '/api/v1/parishes/busy/intentions');
t('reader GET is limited to 300/hour per IP (301st -> 429)', $codes === [200, 200, 200] && $s === 429, json_encode($codes) . " $s");
reset_state();
