<?php
// Creates a config file that uses your REAL mailbox, by asking you for the details.
// The password is typed here (hidden) and written only to the new file, mode 600 --
// it never goes into git, chat or shell history.
// Run:  php api/cli/setup-mail.php
// Result: .external/uo-private/config-realmail.php (git-ignored); use it with
//   UO_CONFIG_PATH=.external/uo-private/config-realmail.php php api/cli/send-test-mail.php you@example.org
if (PHP_SAPI !== 'cli') { exit; }

$root = dirname(__DIR__, 2);
$base = getenv('UO_CONFIG_PATH') ?: "$root/.external/uo-private/config.php";
$out = $argv[1] ?? "$root/.external/uo-private/config-realmail.php";
if (!is_file($base)) { fwrite(STDERR, "Base config not found: $base\nRun `bash api/dev/serve.sh` once first (it creates it).\n"); exit(1); }
$cfg = include $base;

function ask(string $label, string $default = '', bool $hidden = false): string {
    echo $label . ($default !== '' ? " [$default]" : '') . ': ';
    if ($hidden) { @system('stty -echo 2>/dev/null'); }
    $line = trim((string)fgets(STDIN));
    if ($hidden) { @system('stty echo 2>/dev/null'); echo "\n"; }
    return $line === '' ? $default : $line;
}

echo "Real mail settings (press Enter to accept the value in brackets).\n";
$host = ask('SMTP server', 'mail.spacemail.com');
$port = (int)ask('SMTP port', '465');
$enc  = ask("Encryption ('ssl' for port 465, 'tls' for 587)", $port === 587 ? 'tls' : 'ssl');
$user = ask('Mailbox / username', 'admin@theuniversaloffice.com');
$pass = ask('Mailbox password (typing is hidden)', '', true);
if ($pass === '') { fwrite(STDERR, "No password entered; nothing written.\n"); exit(1); }
if (!in_array($enc, ['ssl', 'tls'], true)) { fwrite(STDERR, "Encryption must be ssl or tls.\n"); exit(1); }

$cfg['mail'] = ['driver' => 'smtp', 'host' => $host, 'port' => $port, 'encryption' => $enc,
                'username' => $user, 'password' => $pass,
                'from_email' => $user, 'from_name' => 'The Universal Office'];
@mkdir(dirname($out), 0700, true);
file_put_contents($out, "<?php\n// Generated by api/cli/setup-mail.php -- contains a real password. Never commit.\nreturn " . var_export($cfg, true) . ";\n");
chmod($out, 0600);
echo "Written: $out (private, git-ignored).\n";
